print("\n--- NAME ANALYSIS REPORT ---")
name = input("What is your name? ")
print("Hello, " + name + "! Welcome to Python programming.")
print("---------------------------")
clean_name= name.replace(" ", "").upper()
print("Your name in uppercase without spaces is: " + clean_name)
print("---------------------------")
length = len(clean_name)
print("The length of your name (without spaces) is: " + str(length))
print("---------------------------")
a=clean_name.count("A")
e=clean_name.count("E")
i=clean_name.count("I")
o=clean_name.count("O")
u=clean_name.count("U")
print("The number of vowels in your name is: " + str(a+e+i+o+u))
print("---------------------------")
reversed_name = clean_name[::-1]
print("Your name reversed is: " + reversed_name)